/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author aya
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    String gender;
    String  knowledge;
    String date;
      NewJFrame f=new NewJFrame();
    public NewJFrame1() {
        initComponents();
        show_user();
    }
    public ArrayList<UserInfo> userList(){
    
    ArrayList<UserInfo> us=new ArrayList<>();
    try{
        System.out.print("hello");
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","");
        
         String qry="SELECT * FROM infouser";
         //   PreparedStatement st=con.prepareStatement(qry);
         Statement st=con.createStatement();
             ResultSet rs=st.executeQuery(qry);
             UserInfo user;
             while(rs.next()){    
           user =new  UserInfo(
                   rs.getInt("id"),rs.getString("name"),rs.getString("job"),rs.getString("birthday"),rs.getString("address"), rs.getString("gender"),rs.getString("knowledge")) ;
              us.add(user);
             }
        
        
    }
    catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    return us;
    }
    public void show_user(){
        ArrayList<UserInfo> listUser=userList();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        Object row[]=new Object[7];
        for(int i=0;i<listUser.size();i++){
            row[0]=listUser.get(i).getId();
            row[1]=listUser.get(i).getName();
            row[2]=listUser.get(i).getJob();
               row[3]=listUser.get(i).getBirthday();
            row[4]=listUser.get(i).getAddress();
            row[5]=listUser.get(i).getGender();
                 row[6]=listUser.get(i).getKnowledge();
                 model.addRow(row);
        }  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        job = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        birthday = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kowledge = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/lcj.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel4.setText("Birthday");
        jLabel4.setAlignmentY(0.8F);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 100, 90, 31);

        add.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        add.setPreferredSize(new java.awt.Dimension(50, 31));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(160, 150, 90, 30);

        jButton1.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 320, 90, 40);

        job.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        job.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        job.setPreferredSize(new java.awt.Dimension(50, 31));
        job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobActionPerformed(evt);
            }
        });
        jPanel1.add(job);
        job.setBounds(160, 60, 90, 30);

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel5.setText("knowledge");
        jLabel5.setAlignmentY(0.8F);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 250, 90, 31);

        female.setBackground(new java.awt.Color(0, 102, 51));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        female.setText("Female");
        female.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female);
        female.setBounds(260, 200, 80, 29);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel3.setText("Job");
        jLabel3.setAlignmentY(0.8F);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 60, 90, 31);

        jButton3.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.setToolTipText("");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(220, 320, 90, 40);

        jButton2.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jButton2.setText("Edit");
        jButton2.setToolTipText("");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 320, 90, 40);

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel6.setText("Add New Data ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 20, 170, 23);

        male.setBackground(new java.awt.Color(0, 102, 51));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        male.setText("Male");
        male.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(170, 200, 70, 31);

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        jLabel7.setAlignmentY(0.8F);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 150, 90, 31);

        jButton4.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jButton4.setText("Reset");
        jButton4.setToolTipText("");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(320, 320, 90, 40);

        birthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jPanel1.add(birthday);
        birthday.setBounds(160, 100, 180, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Job", "birthday", "Address", "Gender", "Knowledge"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 380, 430, 170);

        kowledge.setBackground(new java.awt.Color(0, 102, 51));
        kowledge.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        kowledge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "C++", "Python", "Flutter" }));
        kowledge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jPanel1.add(kowledge);
        kowledge.setBounds(210, 250, 90, 30);

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel8.setText("Gender ");
        jLabel8.setAlignmentY(0.8F);
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 200, 90, 31);

        address.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/lcj.jpg"))); // NOI18N
        jPanel1.add(address);
        address.setBounds(0, 0, 440, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

    }//GEN-LAST:event_addActionPerformed

    private void jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobActionPerformed

    }//GEN-LAST:event_jobActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
           
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","");
            String qry="insert into infouser(name,job,birthday,address,gender,knowledge)values(?,?,?,?,?,?)";
            PreparedStatement st=con.prepareStatement(qry);
            

  System.out.print(f.name);
           st.setString(1,f.name);
           st.setString(2,job.getText());
           SimpleDateFormat dt;
              //    JOptionPane.showMessageDialog(null, "insertedddddddddddd successfully");
                dt = new SimpleDateFormat("yyyy-MM-dd");
                date=dt.format(birthday.getDate());
                st.setString(3,date);
           st.setString(4,add.getText() );
           if(male.isSelected())
           {
               gender="Male";
           }
           if(female.isSelected())
           {
               gender="Female";
           }
           st.setString(5,gender);
           knowledge=kowledge.getSelectedItem().toString();
               st.setString(6,knowledge);
               
                st.executeUpdate();
                  DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.setRowCount(0);
                show_user();
                 JOptionPane.showMessageDialog(null, "inserted successfully");
                st.close();
               con.close();
                

           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","");
        int row =jTable1.getSelectedRow();
        String value=(jTable1.getModel().getValueAt(row,0).toString());
        
        String qry="UPDATE infouser SET name=?,job=?,birthday=?,address=?,gender=?,knowledge=? where id="+value;
      
          PreparedStatement st=con.prepareStatement(qry);

  System.out.print(f.name);
           st.setString(1,f.name);
           st.setString(2,job.getText());
           SimpleDateFormat dt;
              //    JOptionPane.showMessageDialog(null, "insertedddddddddddd successfully");
                dt = new SimpleDateFormat("yyyy-MM-dd");
                date=dt.format(birthday.getDate());
                st.setString(3,date);
           st.setString(4,add.getText() );
           if(male.isSelected())
           {
               gender="Male";
           }
           if(female.isSelected())
           {
               gender="Female";
           }
           st.setString(5,gender);
           knowledge=kowledge.getSelectedItem().toString();
               st.setString(6,knowledge);
               
                st.executeUpdate();
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.setRowCount(0);
                show_user();
                 JOptionPane.showMessageDialog(null, "update  successfully");
                st.close();
con.close();

        
        
        
        } 
        
        
        
        catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
           
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","");
        int row =jTable1.getSelectedRow();
        String value=(jTable1.getModel().getValueAt(row,0).toString());
        
        String qry="DELETE FROM  infouser where id="+value;
      
          PreparedStatement st=con.prepareStatement(qry);
                st.executeUpdate();
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.setRowCount(0);
                show_user();
                 JOptionPane.showMessageDialog(null, "DELETE   successfully");
                st.close();
                con.close();

     
        } 
        
        
        
        catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
           
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
    //   NewJFrame.name=(model.getValueAt(i,1).toString());
        job.setText(model.getValueAt(i, 2).toString());
      
              try{
                  int srow=jTable1.getSelectedRow();
                Date date=new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(srow, 3));
                birthday.setDate(date);
          }
               catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }      add.setText(model.getValueAt(i, 4).toString());
                String gender=model.getValueAt(i,5 ).toString();
                if(gender.equals("Male"))
                    male.setSelected(true);
                else
                    female.setSelected(true);
                    
                String knowledge=model.getValueAt(i,6 ).toString();
                
                    switch(knowledge)
                    {
                        case "Java":
                             kowledge.setSelectedIndex(0);
                        break;
                        case "C++":
                              kowledge.setSelectedIndex(1);
                             break;
                        case "Python":
                               kowledge.setSelectedIndex(2);
                                   break;
                        case "Flutter":
                               kowledge.setSelectedIndex(3);
                                         break;
                    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        job.setText("");
        birthday.setCalendar(null);
      add.setText("");
      buttonGroup1.clearSelection();
      kowledge.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JLabel address;
    private com.toedter.calendar.JDateChooser birthday;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField job;
    private javax.swing.JComboBox<String> kowledge;
    private javax.swing.JRadioButton male;
    // End of variables declaration//GEN-END:variables
}
